org.gradle.jvmargs=-Xmx8G -Dmixin.debug.dumpTargetOnFailure=true
org.gradle.daemon=false
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7897
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.2)
forge_version=47.1.44
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.06.26-1.20.1
mod_id=nffgirls
archive_base_name=nffgirls-1.20.1
mod_name=NFF: Girls
mod_license=LGPL-3.0
mod_group_id=net.sodiumzh.nff.girls
mod_authors=SodiumZH
mod_description=Enjoy your Minecraft days with monster girls!
mixinextras_version=0.3.1
mixinextras_min_version=0.3.0

mod_version=0.2.33.2
filename_version=0.2.33.2
nfu_version=0.2.33.3
nfu_version_range=[0.2.33.3, 0.2.34)
services_version=0.2.33.2
services_version_range=[0.2.33.2, 0.2.34)
hmag_version_range=[9.0.20, 10.0)
jei_version=15.2.0.27
jei_version_range=[15, 16)
patchouli_version=84.1
patchouli_version_range=[1.20.1-80,)